### ISSUE TITLE
关于刷新的问题

### ISSUE THREAD

**Issue by hailing0921** [mcxtzhang/SuspensionDecorationIndexBar#9]
每次点击更新数据源之后顶部那4个都会发生顺序的变化，没找到问题在哪
还有比如把A下面的数据全部删掉后右侧的索引没有删掉
这两个问题解决了，要是再加个侧滑出来删除按钮的话那就完美了

**Comment by mcxtzhang** [comment]
“每次点击更新数据源之后顶部那4个都会发生顺序的变化，没找到问题在哪”
这个bug已经解决。
“要是再加个侧滑出来删除按钮的话那就完美了”
这个feature已经添加

**Comment by mcxtzhang** [comment]
"还有比如把A下面的数据全部删掉后右侧的索引没有删掉"
此时应该通知IndexBar.invalidate(),
